Add charts cache for build command
helmwave/helmwave pull request #549
Opened 2023-02-02 10:56 UTC by DemitrSpb

Добавил опцию --charts-cache-dir для build команды
Включает кэширование хелм-чартов в указанной директории
- берет чарт из этого кэша, если там есть.
- иначе скачивает и добавляет в кэш

Это понадобилось для того, чтобы после build иметь все необходимые артефакты в папочке, которую можно перенести в закрытый контур и там развернуть без доступа к репозиториям.

Есть, конечно, костыль через темплэйт и переменные типа USE_LOCAL_CACHE=1
```
{{ if eq USE_LOCAL_CACHE 1 }}
chart: cache/chart-1.0.0.tgz
{{ else }}
chart:
  name: repo/chart
  version: 1.0.0
{{ end }}  
```
Но этот подход оказался не удобный в использовании и сложно поддерживаемый в CI

Как бонус, при использовании кэша пропадает два лишних скачивания чарта: в buildReleaseManifest и в DiffLive

2023-02-02 11:46 UTC, Blobson commented
Появилось предложение по-умолчанию хранить кеш чартов в папке `.helmwave`. Что скажете?

2023-02-02 11:48 UTC, r3nic1e commented
@DemitrSpb @Blobson а разве это не уже сделано?

```
❯ cat .helmwave/planfile | grep charts
      url: https://prometheus-community.github.io/helm-charts
        name: .helmwave/charts/prometheus@prometheus-system/kube-prometheus-stack-43.2.0.tgz
❯ ls -lA .helmwave/charts/prometheus@prometheus-system
total 808
-rw-r--r--  1 r3nic1e  staff  413343 Jan 24 15:58 kube-prometheus-stack-43.2.0.tgz
```

Код живет тут - https://github.com/helmwave/helmwave/blob/main/pkg/plan/build_charts.go

2023-02-02 11:51 UTC, r3nic1e commented
Правда, единственное отличие существующего кода от предложенного - он не дедуплицирует чарты

2023-02-02 12:00 UTC, DemitrSpb commented
@r3nic1e 
План файл используется для `up` и он собран с определенными настройками. 
А нам необходимо все перебилживать в закрытом контуре с новыми настройками. Т.е. нужен кэш именно в build, а он не использует план.

2023-02-02 12:16 UTC, DemitrSpb commented on pkg/cache/charts_cache.go
> +	chartFile := fmt.Sprintf("%s/%s-%s.tgz", c.cacheDir, chartName, version)
Вечно про винду забываю. Исправлю.

2023-02-02 12:16 UTC, DemitrSpb commented on pkg/cache/charts_cache.go
> +	if err := helper.CopyFile(file, c.cacheDir); err != nil {
Точно. Хотел ведь и забыл. Спс

2023-02-02 14:12 UTC, Blobson commented
Как думаете? 
Стоит ли добавить следующие два пункта в PR:
  - включить по-умолчанию кеш и задать `HELMWAVE_CHARTS_CACHE_DIR=$HELMWAVE_PLANDIR/charts`
  - при запуске `helmwave build` удалять `HELMWAVE_PLANDIR` не полностью оставляя кеш нетронутым

2023-02-02 14:41 UTC, DemitrSpb commented
@r3nic1e Скажи пож-та, мне надо какой-то changelog добавить? 
https://github.com/helmwave/helmwave/actions/runs/4073759885/jobs/7019156468

2023-02-02 14:42 UTC, r3nic1e commented
@Blobson

- Кеш по умолчанию - предлагаю сейчас не делать, а включить на следующем миноре. На всякий случай, чтобы при наличии ошибки не начало у всех подряд разваливаться
- Если я правильно понимаю, оно сейчас так и работает - https://github.com/helmwave/helmwave/blob/main/pkg/plan/export.go#L15. Правда, оно сначала билдит, а потом уже удаляет. И кеши в текущем варианте тоже не трогаются

2023-02-02 14:43 UTC, r3nic1e commented
@DemitrSpb если не лень, то вот этой штукой интуитивно легко добавляется - https://github.com/miniscruff/changie
Если лень, то я потом сам напишу

2023-02-02 14:44 UTC, r3nic1e commented
Тут все равно autoassign развалился, так что так и так CI будет красным :(

2023-02-02 15:49 UTC, r3nic1e commented on pkg/cache/charts_cache.go
> +	if err := helper.CopyFile(file, c.cacheDir); err != nil {
Еще вызовов `RLock` и `RUnlock` не хватает при поиске в кеше

2023-02-02 19:12 UTC, DemitrSpb commented on pkg/cache/charts_cache.go
> +	if err := helper.CopyFile(file, c.cacheDir); err != nil {
Добавил

2023-02-02 19:13 UTC, DemitrSpb commented on pkg/cache/charts_cache.go
> +	chartFile := fmt.Sprintf("%s/%s-%s.tgz", c.cacheDir, chartName, version)
Исправил

2023-02-03 06:21 UTC, r3nic1e commented on pkg/cache/charts_cache.go
> +	if err := helper.CopyFile(file, c.cacheDir); err != nil {
Если юзать RWMutex, то нужно при чтении делать RLock и RUnlock

2023-02-03 06:27 UTC, r3nic1e requested changes
Один маленький коммент остался про мьютекс :)

2023-02-03 08:23 UTC, DemitrSpb commented on pkg/cache/charts_cache.go
> +	if err := helper.CopyFile(file, c.cacheDir); err != nil {
Спасиб. 
Я с go фактически не знаком, вот и косячу :)

2023-02-03 08:30 UTC, r3nic1e approved these changes

2023-02-03 08:31 UTC, merged